#!/bin/bash

if which zsh >&/dev/null; then
  zsh -c zrec
fi

# Make sure synced with $LESSKEY in .shared_env
if which lesskey >/dev/null 2>&1; then
  lesskey -o ~/.less
fi

#~/.cfg-post.d/fcron

# vim:fenc=utf-8:ft=sh:
